### ISSUE TITLE
Feature: extract all hyperlinks from a docx file

### ISSUE THREAD

**Issue by synox** [coderthoughts/docxtools#3]
I need a list of links, so I can run docxtools for each link.

**Comment by bosschaert** [comment]
Could you elaborate a bit please? Links could be to anything... but I guess you mean links to other docx files? Would you maybe have an example please?

**Comment by synox** [comment]
I mean any hyperlinks, usually to HTTP endpoints. 

I have a simple script https://github.com/hlxsites/24life/blob/806959c89b6a92bf228d160905ccdedde9a033f5/tools/validation/rewrite-links.mjs#L84-L91 that does the following: 

- for each docx file: 
  1. get all links (with `pandoc`)
  2. check if a transformation exists (using `redirects.json`)
  3. apply replace-link with `docxtools`

I currently use `pandoc` to collect all the links. If `docxtools` could list the links (like `list-links` command), my process could be simplified.
