### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by amol-anand** [coderthoughts/docxtools#5]
It would be nice to know which particular file the error occurred on.

Currently, when errors are thrown, it's not clear which file it errored on as shown below:

`find * -name "*.docx" -exec ~/Applications/docxtools {} replace-links https://ABC/ https://DEF/ \;`

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArchive("Invalid zip header")', src/bin/main.rs:79:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'unknown entity reference &amp;', /Users/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xml_dom-0.2.6/src/shared/text.rs:84:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by bosschaert** [comment]
I believe this error is now fixed. In general (if possible) error messages now include the original file that was being processed. Closing as fixed.
